version: 2.1
orbs:
    node: circleci/node@4.1.0
    aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Install Back-End/API Dependencies
          command: |
            npm run api:install
      - run:
          name: Build Front-End
          command: |
            npm run frontend:build
      - run:
          name: Build Back-End/API
          command: |
            npm run api:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - run:
          name: Front-End deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End/API deploy
          command: |
            npm run api:deploy
workflows:
  udagram:
    jobs:
      - build
      - deploy
